### ISSUE TITLE
Rankings columns

### ISSUE THREAD

**Issue by PTL929** [chromix/draftindepth#3]
Remove Notes because it doesn't display anything and put in "Rating" and "Projected Round" would be good.

BTW "Projected Round" is a string of letters and numbers up to 8 characters long.

Thanks

**Comment by PTL929** [comment]
If there is space "Projected Round" would be good too.

**Comment by chromix** [comment]
I would say just projected round, since rating is implied by the rankings (in theory). Anyway it would actually take up a bit more space.

**Comment by chromix** [comment]
Fix is up... confim
